### ISSUE TITLE
Unable to Insert Verses from Song of Solomon

### ISSUE THREAD

**Issue by cjulin6651** [tim-hub/obsidian-bible-reference#126] opened 2023-09-04 12:53 UTC
**Describe the bug**
I cannot for the life of me insert any passages from The Song of Solomon. I've tried every abbreviation I can think of as well as Song of Songs, capitalized, uncapitalized, spaces, no spaces, etc.

**To Reproduce**
1. Try to add any verse from "Song of Solomon."
2. 
**Expected behavior**
No books pull up. 

**What Device Do You Use(please complete the following information):**
 - Device: iPhone 12 mini
 - OS: iOS 16.6
![IMG_C9467675A36A-1](https://github.com/tim-hub/obsidian-bible-reference/assets/38538687/d6d7a1e7-c880-40ac-9e99-462a299b1998)

**Comment by tim-hub** [comment] 2023-09-04 21:20
Thanks for this issue. 

I realized this book name has not been set properly.

- `sos1:1` or `songofsongs1:1` will work
- but `songofsolomons1:1`  will not work


this issue is related to this as well https://github.com/tim-hub/obsidian-bible-reference/issues/79


Need to find a time to make the book name trigger better.

**Comment by cjulin6651** [comment] 2023-09-05 12:46
Awesome! Thank you!

**Comment by tim-hub** [comment] 2023-09-05 19:40
Duplicate of #79

**Comment by tim-hub** [comment] 2023-10-01 09:17
This should be fixed in version 2.2.0, Thanks for the patience.

https://github.com/tim-hub/obsidian-bible-reference/releases/tag/2.2.0

**Closed by tim-hub** 2023-10-01 09:17 UTC
Labels: bug

**Comment by maharielrosario** [comment] 2025-04-06 15:30
@tim-hub  I am noticing that "Song of Solomon"  or "Song of Songs" are not being picked up on [25.04.01-2](https://github.com/tim-hub/obsidian-bible-reference/releases/tag/25.04.01-2).  Might be because of spacing in the name?

**Comment by android272** [comment] 2025-10-26 18:05
I think that this should be added to the how to use wiki and an example in the Obsidian plugin page.
