### ISSUE TITLE
Does not work on mobile

### ISSUE THREAD

**Issue by ickc** [tim-hub/obsidian-bible-reference#55] opened 2022-08-20 00:28 UTC
https://github.com/tim-hub/obsidian-bible-reference/blob/master/manifest.json#L9 seems to indicate that it would work on mobile, but when testing it on iPad and iPhone, it doesn't seem to work. Any idea? Thanks.

**Comment by russbonchu** [comment] 2022-08-20 23:01
I would like to +1 this as it works fine on my Mac but nothing seems to happen on my iPhone. This would be fantastic on my phone as I take notes in church and this would be a great way to import the scripture references.

**Comment by russbonchu** [comment] 2022-08-26 14:32
I am using Obsidian 1.3.1 (67) which is the latest version, and the plugin is up to date. i have tried several Bible versions and nothing happens. I would love to be able to use this in church with sermon notes.

**Comment by tim-hub** [comment] 2022-09-02 05:24
Oh, I haven't gotten an iOS device for testing, I only tried on Android, and it worked as on desktop, I am not sure, is it possible related to any iOS app policy?

**Comment by russbonchu** [comment] 2022-09-03 15:03
There's no policy that I'm aware of but not being a developer myself I could be wrong. I can do some research and check.

Thanks for looking into this, and thanks for creating this plugin!

—
Russell Bonchu, III
***@***.***
https://russbonchu.site
2163751801

**Comment by sword218** [comment] 2022-10-10 23:34
Api:bible api can work on the phone,but API:Bolls can’t

**Comment by sword218** [comment] 2022-10-10 23:34
![Uploading E0C6B1BE-8BDD-405C-B522-9A5758BD77A3.jpeg…]()

**Comment by sword218** [comment] 2022-10-10 23:34
![3A7AA120-F268-4BAE-A9A5-54153AC2E632](https://user-images.githubusercontent.com/115510765/194967496-3a7d7359-a767-458c-a6ad-0ad21a3f4b75.jpeg)

**Comment by sword218** [comment] 2022-10-10 23:35
![Uploading D4B8A101-8B7C-48D2-BD81-A2DF84599646.jpeg…]()

**Comment by sword218** [comment] 2022-10-10 23:36
![57121591-0455-4DC6-B3F9-B44F9626CE7E](https://user-images.githubusercontent.com/115510765/194967598-0a27136f-b007-4fef-b9fa-f1af475b499a.jpeg)

**Comment by BMonsalvatge** [comment] 2022-12-04 20:01
I can't seem to get either API working for me at the moment.

**Comment by JPT62089** [comment] 2023-01-09 02:21
Just tested this out on my Pixel 6 Pro and ran into the same issue. Bible API works fine but Bolls does not. We'll have to see if there are any functions or something that aren't supported on Android. 

Is anyone able to confirm if Bible API works for Apple devices? Or does neither work?

**Comment by JPT62089** [comment] 2023-01-11 05:28
Ok I was finally able to get some time to look into this further. On Android this appears to be an issue only with Bolls Life. The request is getting blocked by CORS policy as seen in the screenshot.

![image](https://user-images.githubusercontent.com/1808107/211722598-b0eeb286-0892-447d-acd2-ce326fc8cd03.png)

`Access to fetch at 'https://bible-api-bff.bai.uno/bolls-life/ESV/43/1/' from origin 'http://localhost' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'app://obsidian.md' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

@tim-hub, any reason why this is using https://bible-api-bff.bai.uno/bolls-life rather than https://bolls.life/get-text for the API URL? I changed my local main.js to the latter and it immediately worked perfectly on my android phone. In the meantime I might spin up a PR a change to the latter in case we want to switch to it over the current url

**Comment by tim-hub** [comment] 2023-01-31 09:21
> Ok I was finally able to get some time to look into this further. On Android this appears to be an issue only with Bolls Life. The request is getting blocked by CORS policy as seen in the screenshot.
> 
> ![image](https://user-images.githubusercontent.com/1808107/211722598-b0eeb286-0892-447d-acd2-ce326fc8cd03.png)
> 
> `Access to fetch at 'https://bible-api-bff.bai.uno/bolls-life/ESV/43/1/' from origin 'http://localhost' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'app://obsidian.md' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
> 
> @tim-hub, any reason why this is using https://bible-api-bff.bai.uno/bolls-life rather than https://bolls.life/get-text for the API URL? I changed my local main.js to the latter and it immediately worked perfectly on my android phone. In the meantime I might spin up a PR a change to the latter in case we want to switch to it over the current url

In the beginning of trying bolls like api, I found there was a CORS error stopping the plugin to consume it, 

But it looks like the issue is gone now.

Thanks for raising up and testing on this. :)

**Comment by tim-hub** [comment] 2023-01-31 09:22
the issues supposed to be fixed in release 1.4.0 after PR #73

**Closed by tim-hub** 2023-01-31 09:22 UTC
Labels: bug
